# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site informations
title: 狐狸哒黍·小馒头
email: tjian123@foxmail.com
author: tjian
description: > # this means to ignore newlines until "baseurl:"
  狐狸哒黍的个人小站，包括但不限于以下内容：技术积累、生活感想、书籍推荐和创意点子。
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#

permalink: /:year/:month/:day/:title

github_username: tjian123
google_plus_username: tjian

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
sass:
  style: compressed
excerpt_separator: <!--more--> #用于显示文章摘要

# Default style: default, dack, light
bodyClass: default-style

include: [_pages]
exclude: [TODO, README.md]

# 分页 gitpage只支持在index.html中使用，故弃之
# paginate            : 10          # 定义每页数量
# paginate_path       : "page:num"  # 定义分页结果
# gems                : ['jekyll-paginate']
# 

# 是否开启背景图片
enable_bg_img: false