# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 狐狸哒黍.小馒头
email: tjian123@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  狐狸哒黍的个人小站，包括但不限于以下内容：技术积累、生活感想、书籍推荐和创意点子.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: tjian123
github_username:  tjian123

# Build settings
markdown: kramdown

# Default style: default, dack, light
bodyClass: dack-style
